name: near-willem-workspaces-init
on: push
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        node-version: ['14.0.0', 14, 15, '16.0.0', 16]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run tests
        run: npm i fs-extra && node packages/init/scripts/test.js